<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

<ItemGroup><ProjectReference Include="..\..\ApiGestion\Gestion.Logica\Gestion.Logica.csproj" /></ItemGroup><ItemGroup><ProjectReference Include="..\..\ApiGestion\Gestion.Logica\Gestion.Logica.csproj" /></ItemGroup></Project>
